/* CPSC 471 Fall 2014
 * SQL Tables: Relational Model
 * Submitted by Spencer Howe, Tristan Schorn, Arnold Padillo
 * 
 * NOTES:
 *	- Can test with http://sqlfiddle.com/ 
 *
 * TODO:
 * - Add triggers
 * - Inserting values in the tables now that they are initialized
 * - Implement foreign keys
 *
 */

CREATE TABLE Vehicle(
	SERIAL_NO INT PRIMARY KEY NOT NULL,
	CURR_ODOMETER INT NOT NULL,
	FUEL_TYPE VARCHAR (20) NOT NULL,
	PLATE_NO VARCHAR (20) NOT NULL,
	COLOUR VARCHAR (20) NOT NULL,
	MODEL VARCHAR (20) NOT NULL,
	BASE_COST DECIMAL(10, 2) NOT NULL, -- Max of 10 Digits, 2 numbers after decimal
	MAKE VARCHAR(20) NOT NULL,
	NO_SEATS INT NOT NULL,
	TYPE VARCHAR(20)
);

CREATE TABLE Branch(
	BRANCH_NO INT PRIMARY KEY NOT NULL,
	LOCATION VARCHAR(30) NOT NULL,
	ADDRESS VARCHAR(30) NOT NULL,
	BRANCH_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE Customer(
	LICENSE_NO INT PRIMARY KEY NOT NULL,
	CUST_NAME VARCHAR (30) NOT NULL,
	PHONE_NO INT NOT NULL,
	CREDCARD_NO INT NOT NULL
);

CREATE TABLE Employee(
	EMPLOYEE_ID INT PRIMARY KEY NOT NULL,
	SUPERVISOR_ID INT NOT NULL,
	EMP_NAME VARCHAR (30) NOT NULL
);

CREATE TABLE WorksAt(
	BRANCH_NO INT NOT NULL,
	POSITION VARCHAR (30) NOT NULL,
	EMP_ID INT NOT NULL
);

CREATE TABLE Rental(
	RENTAL_NO INT PRIMARY KEY NOT NULL,
	CUST_LICEN INT NOT NULL,
	BRANCH_NO INT NOT NULL,
	EMP_NAME VARCHAR (30) NOT NULL,
	VEH_NO VARCHAR (30) NOT NULL
);


